# Generated by Django 3.1.2 on 2020-10-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddress', models.GenericIPAddressField()),
                ('friendlyName', models.CharField(blank=True, max_length=200)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iotemperature.cluster')),
            ],
            options={
                'verbose_name': 'Sensore',
                'verbose_name_plural': 'Sensori',
            },
        ),
        migrations.CreateModel(
            name='Misurazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('date', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotemperature.sensor')),
            ],
            options={
                'verbose_name': 'misurazione',
                'verbose_name_plural': 'misurazioni',
            },
        ),
    ]
