# Generated by Django 3.1.1 on 2020-09-28 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('IPAddress', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('friendlyName', models.CharField(blank=True, max_length=200)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iotemperature.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Misurazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('date', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotemperature.sensor')),
            ],
        ),
    ]
