# Generated by Django 3.1.2 on 2020-10-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotemperature', '0002_auto_20201020_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
