# Generated by Django 3.1.2 on 2020-10-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotemperature', '0003_auto_20201020_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='IPAddress',
            field=models.GenericIPAddressField(unique=True, verbose_name='Indirizzo IP'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='friendlyName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome'),
        ),
    ]
